image: python:latest

before_script:
  - python -V
  - pip install poetry
  - pip install nvidia-cublas-cu11-11.10.3.66 nvidia-cuda-nvrtc-cu11-11.7.99 nvidia-cuda-runtime-cu11-11.7.99 nvidia-cudnn-cu11-8.5.0.96
  - poetry install --with test

test:
  stage: test
  script:
    - poetry run pytest