image: python:latest

stages:
  - build
  - test

before_script:
  - python -V
  - pip install poetry
  - pip install torch --index-url https://download.pytorch.org/whl/cpu

build:
  stage: build
  script:
    - poetry install

test:
  stage: test
  script:
    - poetry run pytest