image: nvidia/cuda:10.2-base

stages:
  - build
  - test

before_script:
  - python -V
  - pip install poetry

build:
  stage: build
  script:
    - poetry install

test:
  stage: test
  script:
    - poetry run pytest