image: python:latest

stages:
  - build
  - test

before_script:
  - python -V
  - pip install poetry
  - pip install torch --index-url https://download.pytorch.org/whl/cpu
  - poetry install --with test

build:
  stage: build
  script:
    - echo "build completed"

test:
  stage: test
  script:
    - poetry run pytest