image: python:latest

stages:
  - test
  - docs

before_script:
  - python -V
  - pip install .

test:
  stage: test
  script:
    - pip install pytest
    - pytest tests/
  rules:
    - if: $CI_COMMIT_BRANCH == $CI_DEFAULT_BRANCH

docs:
  script:
    - pip install sphinx
    - make html
  rules:
    - if: $CI_COMMIT_BRANCH == $CI_DEFAULT_BRANCH