image: python:latest

stages:
  - build
  - test

before_script:
  - python -V
  - pip install poetry
  - poetry install --with test
  - export CUDA_VISIBLE_DEVICES=""

build:
  stage: build
  script:
    - echo "build completed"

test:
  stage: test
  script:
    - poetry run pytest