image: python:latest

stages:
  - build
  - test

build:
  stage: build
  script:
    - python -V
    - pip install poetry
    - pip install torch --index-url https://download.pytorch.org/whl/cpu
    - poetry install --with test

test:
  stage: test
  script:
    - poetry run pytest