image: python:3.9-slim-buster

variables:
  PIP_CACHE_DIR: "$CI_PROJECT_DIR/.cache/pip"
  
cache:
  paths:
    - .cache/pip
    - .venv

before_script:
  - python --version ; pip --version  # For debugging
  - pip install poetry
  - poetry config virtualenvs.in-project true
  - poetry install

test:
  script:
    - poetry run pytest

pages:
  script:
    - poetry install -E docs
    - cd docs
    - make html
    - mv build/html/ ../public/
  artifacts:
    paths:
      - public
  rules:
    - if: $CI_COMMIT_BRANCH == $CI_DEFAULT_BRANCH


#deploy:
#  stage: deploy
#  script:
#     - poetry build
#     - poetry publish
#  environment: production