name: CI

on:
  push:
    branches:
      - main
      - 'feat/**'
      - 'feature/**'
  pull_request:
    branches:
      - main

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout code
        uses: actions/checkout@v3

      - name: Set up Python
        uses: actions/setup-python@v4
        with:
          python-version: '3.11'  # Use the appropriate version for your project

      - name: Install dependencies
        run: |
          sudo apt-get update
          sudo apt-get install -y make
          sudo apt-get install -y git
          sudo apt-get install -y curl

      - name: Install Poetry
        run: |
          curl -sSL https://install.python-poetry.org | python3 -
          echo "$HOME/.local/bin" >> $GITHUB_PATH

      - name: Install git-secrets
        run: |
          git clone https://github.com/awslabs/git-secrets.git
          cd git-secrets
          sudo make install
          git secrets --install
          git secrets --register-aws
          git secrets --add 'PRIVATE KEY'

      - name: Set up Poetry virtual environment
        run: |
          poetry config virtualenvs.in-project true
          poetry install --with dev,test,docs

      - name: Run Makefile tasks
        run: |
          poetry run make all
